import 'package:http/http.dart' as http;
import 'package:zomato_app/models/Category.dart';
import 'dart:convert';

class ZomatoApiProvider {

  String baseUrl = "https://developers.zomato.com/api/v2.1/categories";

   Future<List<Categories>> fetchCategories(String apiKey) async {
    final response = await http.get("$baseUrl", headers: {'user-key':"908ea12c9d73dea7597e08d714b0f16c"});

    final responseString = jsonDecode(response.body);
    if(response.statusCode == 200)
      return Autogenerated.fromJson(responseString).categories;
    else
      throw Exception('failed to load players');
  }
}